# Dùng Python image chính thức
FROM python:3.10-slim

# Copy file app.py vào container
COPY app.py /app/app.py

# Đặt thư mục làm việc
WORKDIR /app

# Lệnh mặc định khi chạy container
CMD ["python", "app.py"]
