version: "3"

# Network
networks:
  my-network: driver:bridge

# Volumes
volumes:
  dir-site:
    driver_opts:
      device: /sites/
      o: bind

# Services
services:
  # PHP container
  my-php:
    container_name: php-product
    build:
      dockerfile: Dockerfile
      context: ./php/
    hostname: php
    restart: always
    network:
      - my-network
    volumes:
      - dir-site: /home/sites/
  # HTTPD container
  my-httpd:
    container_name: c-httpd01
    images: "httpd:latest"
    hostname: httpd
    restart: always
    network:
      - my-network
    volumes:
      - dir-site:/home/sites/
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "9999:80"
      - "443:443"
  # MySQL container
  my-sql:
    container_name: mysql-product
    images: "mysql:latest"
    hostname: mysql
    restart: always
    network:
      - my-network
    volumes:
      - ./db:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/my.cnf
    enviroment:
      - MYSQL_ROOT_PASSWORD=123abc
      - MYSQL_DATABASE=db_site
      - MYSQL_USER=siteuser
      - MYSQL_PASSWORD=sitepass
